# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd frontend
        npm install
        cd ../backend
        npm install

    - name: Run frontend tests
      run: |
        cd frontend
        npm test

    - name: Run backend tests
      run: |
        cd backend
        npm test
        
    - name: Run linter
      run: |
        cd backend
        npm run lint
    
    - name: Run prettier backend
      run: |
        cd backend
        npm run prettier-check
    
    - name: Run prettier frontend
      run: |
        cd frontend
        npm run prettier-check

    - name: Build
      run: |
        cd frontend
        npm run build
  
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        run: |
          cd frontend
          npm install
          
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start